#!/usr/bin/env python3
"""
CHECK iso/firstboot/boot-art.h. Never write to it.

This used to generate the boot art, and the file's own header says
"Generated by tools/gen-boot-art.py; edit that script, not this file, or the
next run will overwrite your change." That instruction is why the art was
being edited in the header and then lost: running the generator replaced it.

So this no longer generates anything. The art in boot-art.h is the art, it is
hand-maintained, and the only thing left to automate is checking it -- because
every mistake that matters here is invisible in a diff. A dropped character, a
row that is one column too wide, a block that does not fit the console: none of
them show up until the thing boots on real hardware.

Run it after any edit to the art:

    python3 tools/gen-boot-art.py

Exit status is 0 if the art is usable, 1 if it is not. Nothing is written.
"""
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

REPO = pathlib.Path(__file__).resolve().parent.parent
ART = REPO / "iso" / "firstboot" / "boot-art.h"

# What the kernel gives a VGA text console, no matter how big the window is.
COLS, ROWS = 80, 25

fail = 0


def bad(msg):
    global fail
    fail = 1
    print(f"  FAIL  {msg}")


def ok(msg):
    print(f"  ok    {msg}")


def warn(msg):
    """Something the artist probably meant. Not a defect: a shield taller
    than the console is cropped at the bottom and still renders fine, so
    failing on it would just mean nobody ever runs this again."""
    print(f"  warn  {msg}")


if not ART.exists():
    print(f"gen-boot-art: {ART} does not exist")
    sys.exit(1)

raw = ART.read_bytes()
src = raw.decode("utf-8")

print("boot art check")
print()

# ------------------------------------------------------------------ encoding
nonascii = [(i, hex(c)) for i, c in enumerate(raw) if c > 127]
if nonascii:
    bad(f"{len(nonascii)} non-ASCII byte(s), first at offset {nonascii[0][0]} "
        f"({nonascii[0][1]}). "
        f"Copper's terminal output is ASCII: an 8x16 VGA font is indexed by "
        f"byte, so a multi-byte character is two garbage glyphs, not one.")
    print(f"        offsets: {[o for o, _ in nonascii[:12]]}")
else:
    ok("pure ASCII")

# ------------------------------------------------------------------ compiles
# Compile the header the way copper-firstboot.c actually consumes it: as an
# include, with every macro expanded and both arrays indexed.
#
# Compiling the header on its own is much weaker than it looks. An unbalanced
# paren in a #define is legal C as long as nothing ever expands it, so
# "-x c boot-art.h" passes on a header that cannot compile the moment the real
# source says "int rows = COPPER_SHIELD_ROWS;". That gap was hit here: the
# header compiled standalone while the ROWS macro was broken.
TU = """
#include "boot-art.h"
#include <stdio.h>
int main(void) {
    int rows = COPPER_SHIELD_ROWS + COPPER_WORDMARK_ROWS;
    int w = COPPER_SHIELD_WIDTH + COPPER_WORDMARK_WIDTH;
    const char *first = COPPER_SHIELD[0];
    const char *last = COPPER_WORDMARK[COPPER_WORDMARK_ROWS - 1];
    printf("%d %d %s %s\\n", rows, w, first, last);
    return 0;
}
"""

if shutil.which("gcc"):
    with tempfile.TemporaryDirectory() as d:
        d = pathlib.Path(d)
        (d / "boot-art.h").write_text(src, encoding="utf-8")
        (d / "tu.c").write_text(TU, encoding="utf-8")
        r = subprocess.run(["gcc", "-Wall", "-Wextra", "-fsyntax-only",
                            "-I", str(d), str(d / "tu.c")],
                           capture_output=True, text=True)
        noise = [ln for ln in r.stderr.splitlines()
                 if "unused" not in ln and ln.strip()]
        if r.returncode == 0:
            ok("compiles as included, all macros expanded")
            for ln in noise:
                print(f"  note  {ln}")
        else:
            bad("does not compile the way copper-firstboot.c uses it")
            for ln in noise[:12]:
                print(f"        {ln}")
else:
    print("  skip  no gcc here to compile it with")

# ------------------------------------------------------------------ contents
blocks = {}
for name in ("COPPER_SHIELD", "COPPER_WORDMARK"):
    try:
        i = src.index(name + "[] ")
        j = src.index("{", i)
        k = src.index("\n};", j)
    except ValueError:
        bad(f"{name} not found")
        continue
    blocks[name] = [m.group(1) for m in
                    re.finditer(r'^\s*"(.*)",\s*$', src[j + 1:k], re.M)]

if len(blocks) != 2:
    print()
    sys.exit(fail)

for name, rows in blocks.items():
    print()
    label = name.replace("COPPER_", "").lower()
    widest = max(len(r) for r in rows)
    blank = [i for i, r in enumerate(rows) if not r.strip()]

    print(f"{label}: {len(rows)} rows, widest {widest} columns")

    # Losing columns off the right edge destroys part of the drawing, so that
    # is a failure. Losing rows off the bottom only hides the base of a shape,
    # which is a choice, so that is a warning.
    if widest > COLS:
        bad(f"{widest} columns, console has {COLS}. "
            f"The right {widest - COLS} columns will be clipped and never seen.")
    else:
        ok(f"fits horizontally, {COLS - widest} to spare")

    if len(rows) > ROWS:
        warn(f"{len(rows)} rows, console has {ROWS}. "
             f"Rows {ROWS}..{len(rows) - 1} are drawn nowhere: "
             f"{len(rows) - ROWS} row(s) of this never reach the screen.")
    else:
        ok(f"fits vertically, {ROWS - len(rows)} to spare")

    # copper-firstboot() clamps what it prints to this number, and centres on
    # it, so it has to be the real width of the art:
    #   too small -> the drawing is cut off
    #   too large -> nothing is cut, but the block is centred on a width that
    #                is wider than the drawing and sits off to one side
    m = re.search(name + r'_WIDTH\s*=\s*(\d+)', src)
    if m:
        declared = int(m.group(1))
        if declared == widest:
            ok(f"declared _WIDTH matches ({declared})")
        elif declared < widest:
            bad(f"declares _WIDTH {declared}, widest row is {widest}. "
                f"copper-firstboot prints at most _WIDTH columns, so the "
                f"right {widest - declared} column(s) are discarded.")
        else:
            bad(f"declares _WIDTH {declared}, widest row is {widest}. "
                f"Nothing is cut, but centring uses the declared number, so "
                f"the drawing sits {(declared - widest) // 2} column(s) left "
                f"of centre.")

    # rows must be uniform or the shield's diagonals go ragged
    ragged = sorted({len(r) for r in rows})
    if len(ragged) > 1:
        print(f"  note  rows are not padded to a uniform width: {ragged}")
        print(f"        harmless if the short rows are trailing spaces, "
              f"wrong if they carry ink")

    # a lone trailing column is how an off-by-one in a hand edit hides
    if blank:
        print(f"  note  blank row(s): {blank}")

    ink = sorted({c for r in rows for c in r if c not in " "})
    print(f"  ink  {''.join(ink)!r}")

    credit = [i for i, r in enumerate(rows) if "MADE BY" in r or "HANDCRAFT" in r]
    if credit:
        bad(f"credit text on row(s) {credit}")

    # The closing comment above each block restates the row count and width as
    # prose. sizeof computes those correctly every time; the comment is typed
    # by hand and drifts the first time the art is edited. Check it, so it
    # cannot quietly start lying about how big the drawing is.
    # Search a window that starts at this block, not at the top of the file:
    # both closing comments read "/* N rows, widest W columns. */", so a
    # prefix slice attributes the shield's numbers to the wordmark.
    start = src.index(name + "[] ")
    window = src[start:src.index("\n};", start) + 200]
    cm = re.search(
        r"/\*\s*(\d+)\s+rows?,?\s*widest\s+(\d+)\s+columns?\.?\s*\*/", window)
    if cm:
        crows, ccols = int(cm.group(1)), int(cm.group(2))
        if crows == len(rows) and ccols == widest:
            ok(f"trailing comment matches ({crows} rows, {ccols} columns)")
        else:
            bad(f"trailing comment says {crows} rows / {ccols} columns, "
                f"the art is {len(rows)} rows / {widest} columns")

print()
if fail:
    print("boot art is not usable as it stands")
sys.exit(fail)